spring:
  sql.init:
      mode: always
      platform: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/tesa
    username:
    password: hh
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true